### ISSUE TITLE
Preliminary review based on first milestone

### ISSUE THREAD

**Issue by addianto** [mhmmd-attar/mid_tourism_mobile#1]
Hello @kalooshfv @NLexi @Heraldoe @fideraphael @kalooshfv,

The following is my initial assessments on your final group project:

## Project Documentation

-  The documentation has included enough information. It can be enriched by adding badges that display status from GitHub Actions or other status related to the project.
-  Instead of adding `<br>` tags, I think you can use bullet points/unordered lists in the document. Some parts of your document look more natural if bullet points had been used instead.
-  You have documented the persons in charge of each feature/module and were able to distinguish them from user roles that will use the app.

## Release Artefact

-  Try exploring GitHub Actions, especially for automating the build-and-release process.

## Individual Assessments

I have not checked the contributions made by each group member.
Make sure everyone has been invited as developer/collaborator in the group project's GitHub repository.

## Actionable Tasks

-  [ ] Improve the layout of `README.md` file
   - For reference, see [Markdown syntax documentation](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github)
-  [ ] Automate the build and release process using GitHub Actions
-  [ ] Fix any issues in the source code that identified by `flutter analyze`

That is all from me. Keep up the good work.
